export const DRINKSMENU_LIST_REQUEST = "DRINKSMENU_LIST_REQUEST";
export const DRINKSMENU_LIST_SUCCESS = "DRINKSMENU_LIST_SUCCESS";
export const DRINKSMENU_LIST_FAIL = "DRINKSMENU_LIST_FAIL";

export const DRINKSMENU_DETAILS_REQUEST = "DRINKSMENU_DETAILS_REQUEST";
export const DRINKSMENU_DETAILS_SUCCESS = "DRINKSMENU_DETAILS_SUCCESS";
export const DRINKSMENU_DETAILS_FAIL = "DRINKSMENU_DETAILS_FAIL";
