export const FOODMENU_LIST_REQUEST = "FOODMENU_LIST_REQUEST";
export const FOODMENU_LIST_SUCCESS = "FOODMENU_LIST_SUCCESS";
export const FOODMENU_LIST_FAIL = "FOODMENU_LIST_FAIL";

export const FOODMENU_DETAILS_REQUEST = "FOODMENU_DETAILS_REQUEST";
export const FOODMENU_DETAILS_SUCCESS = "FOODMENU_DETAILS_SUCCESS";
export const FOODMENU_DETAILS_FAIL = "FOODMENU_DETAILS_FAIL";
