export const ORDER_CREATION_REQUEST = "ORDER_CREATION_REQUEST";
export const ORDER_CREATION_SUCCESS = "ORDER_CREATION_SUCCESS";
// export const ORDER_CREATION_FAIL = "ORDER_CREATION_FAIL";
// export const ORDER_ADD_REQUEST = "ORDER_ADD_REQUEST";
export const ORDER_ADD_REQUEST = "ORDER_ADD_REQUEST";
export const ORDER_ADD_SUCCESS = "ORDER_ADD_SUCCESS";
export const ORDER_ADD_FAIL = "ORDER_ADD_FAIL";
// export const ORDER_REMOVE_REQUEST = "ORDER_REMOVE_REQUEST";
export const ORDER_REMOVE_SUCCESS = "ORDER_REMOVE_SUCCESS";
// export const ORDER_REMOVE_FAIL = "ORDER_REMOVE_FAIL";
export const ORDER_ITEM_QUANTITY_ADD_SUCCESS =
  "ORDER_ITEM_QUANTITY_ADD_SUCCESS";

export const ORDER_ITEM_QUANTITY_REMOVE_SUCCESS =
  "ORDER_ITEM_QUANTITY_REMOVE_SUCCESS";
